# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 13:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('descrip', models.TextField()),
                ('remark', models.TextField()),
                ('upddate', models.DateTimeField(auto_now=True)),
                ('crateDep', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[(b'0', b'Created'), (b'1', b'Waiting'), (b'2', b'Resolved'), (b'3', b'Pending'), (b'4', b'Handling'), (b'5', b'Closed')], max_length=20)),
                ('package_id', models.CharField(blank=True, max_length=50)),
                ('postman_mobile', models.CharField(blank=True, max_length=20)),
                ('take_mobile', models.CharField(blank=True, max_length=20)),
                ('box_no', models.CharField(blank=True, max_length=5)),
                ('case_from', models.CharField(blank=True, choices=[('0', 'ServicePhone'), ('1', 'WeChat'), ('2', 'Operator'), ('3', 'Other')], max_length=20)),
                ('deliver_time', models.CharField(blank=True, max_length=20)),
                ('take_time', models.CharField(blank=True, max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comm.BaseDepartment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_owner', to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comm.BasePriority')),
                ('terminal_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comm.BaseTerminalInfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('1', 'Re-Assign'), ('2', 'Resolve'), ('3', 'Suspend'), ('4', 'Takeover'), ('5', 'Close')], max_length=30)),
                ('action_brief', models.CharField(blank=True, max_length=64, verbose_name='Action Brief')),
                ('action_detail', models.TextField(blank=True, max_length=256, verbose_name='Action Detail')),
                ('action_time', models.DateTimeField(auto_now=True)),
                ('action_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketmgr.Incident')),
                ('assign_to_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comm.BaseDepartment')),
                ('assign_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_action_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('descrip', models.TextField()),
                ('remark', models.TextField()),
                ('upddate', models.DateTimeField(auto_now=True)),
                ('crateDep', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[(b'0', b'Created'), (b'1', b'Waiting'), (b'2', b'Resolved'), (b'3', b'Pending'), (b'4', b'Handling'), (b'5', b'Closed')], max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comm.BaseDepartment')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comm.BasePriority')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('descrip', models.TextField()),
                ('remark', models.TextField()),
                ('upddate', models.DateTimeField(auto_now=True)),
                ('crateDep', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[(b'0', b'Created'), (b'1', b'Waiting'), (b'2', b'Resolved'), (b'3', b'Pending'), (b'4', b'Handling'), (b'5', b'Closed')], max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comm.BaseDepartment')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comm.BasePriority')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
