# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 06:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmgr', '0003_auto_20160225_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentaction',
            name='assign_to_dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comm.BaseDepartment'),
        ),
        migrations.AlterField(
            model_name='incidentaction',
            name='assign_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
