# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 13:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='BasePriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('remark', models.CharField(choices=[(b'0', b'\xe4\xb8\x80\xe8\x88\xac'), (b'1', b'\xe5\x8a\xa0\xe6\x80\xa5'), (b'2', b'\xe7\xb4\xa7\xe6\x80\xa5'), (b'3', b'\xe7\x81\xbe\xe9\x9a\xbe')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BaseTerminalInfo',
            fields=[
                ('terminal_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('terminal_name', models.CharField(max_length=60)),
                ('terminal_location', models.CharField(max_length=60)),
                ('install_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_cn', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comm.BaseDepartment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
