# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseApps',
            fields=[
                ('app_id', models.IntegerField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BaseErrorItem',
            fields=[
                ('error_id', models.IntegerField(primary_key=True, serialize=False)),
                ('error_name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='BaseErrorType',
            fields=[
                ('error_id', models.IntegerField(primary_key=True, serialize=False)),
                ('errorType', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'INFO'), ('2', 'WARNING'), ('3', 'Critical')], max_length=32)),
                ('server_ip', models.GenericIPAddressField()),
                ('error_msg', models.CharField(max_length=2048)),
                ('is_sendsms', models.BooleanField(default=0)),
                ('is_sendmail', models.BooleanField(default=0)),
                ('sms_status', models.BooleanField(default=0)),
                ('mail_status', models.BooleanField(default=0)),
                ('remark', models.CharField(max_length=256)),
                ('logtime', models.DateTimeField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='errorMonitor.BaseApps')),
                ('error_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='errorMonitor.BaseErrorItem')),
                ('error_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='errorMonitor.BaseErrorType')),
            ],
        ),
    ]
